/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.payroll.view;

import com.java.payroll.connection.DatabaseConn;
import com.java.payroll.user.User;
import com.java.payroll.user.UserManagement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLSyntaxErrorException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class FullSignUp extends javax.swing.JFrame implements UserManagement {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FullSignUp.class.getName());
    
    private Statement stmt = null;
    private ResultSet result = null;
    private static Connection myConn = null;
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FullSignUp().setVisible(true));
    }



    public FullSignUp() {
        getConnection();
        initComponents();
        signUpBtn1.addActionListener((ActionEvent e) -> {
            //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            String userId = empIdTextField1.getText().trim();
            String fullName = fullNameTextField1.getText().trim();
            String email = emailTextField1.getText().trim();
            String trn = trnTextField.getText().trim();
            String street = streetTextField.getText().trim();
            String parish = parishTextField.getText().trim();
            String country = countryTextField.getText().trim();
            String city = cityTextField.getText().trim();
            String gender = genderTextField.getText().trim();
            String day = dayTextField.getText().trim();
            String month = monthTextField.getText().trim();
            String year = yearTextField.getText().trim();
            
            if(userId.isEmpty() || fullName.isEmpty() || email.isEmpty() || trn.isEmpty() || street.isEmpty() || parish.isEmpty() || country.isEmpty() || city.isEmpty() || gender.isEmpty() || day.isEmpty() || month.isEmpty() || year.isEmpty()){
                JOptionPane.showMessageDialog(this, "Empty fields detected!", "Entry status.", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            int dayCon = Integer.parseInt(day);
            int monthCon = Integer.parseInt(month);
            int yearCon = Integer.parseInt(year);
            
            boolean isAdded = createFull(new User( userId,  fullName,  email,  trn,  country,  street,  city,  parish,  gender,  dayCon,  monthCon,  yearCon));
            if(isAdded){
                JOptionPane.showMessageDialog(this, "User added successfully", "Creation Status", JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpLabel1 = new javax.swing.JLabel();
        signUpInfoLabel1 = new javax.swing.JLabel();
        fullNameLabel1 = new javax.swing.JLabel();
        empIdTextField1 = new javax.swing.JTextField();
        empIdLabel1 = new javax.swing.JLabel();
        fullNameTextField1 = new javax.swing.JTextField();
        haveAnAccountLabel1 = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        signUpBtn1 = new javax.swing.JButton();
        dobLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        monthTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        trnLabel = new javax.swing.JLabel();
        trnTextField = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        streetLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderTextField = new javax.swing.JTextField();
        parishLabel = new javax.swing.JLabel();
        parishTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Full Sign Up"); // NOI18N

        signUpLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        signUpLabel1.setForeground(new java.awt.Color(0, 102, 255));
        signUpLabel1.setText("Pay Pulse Sign Up");
        signUpLabel1.setSize(new java.awt.Dimension(60, 30));

        signUpInfoLabel1.setFont(new java.awt.Font("DecoType Naskh", 0, 14)); // NOI18N
        signUpInfoLabel1.setForeground(new java.awt.Color(153, 153, 153));
        signUpInfoLabel1.setText("Register an employee or manager account");

        fullNameLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fullNameLabel1.setText("Full Name");

        empIdTextField1.setForeground(new java.awt.Color(204, 204, 204));
        empIdTextField1.setText(" EMP001");
        empIdTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empIdTextField1.setMinimumSize(new java.awt.Dimension(67, 17));
        empIdTextField1.addActionListener(this::empIdTextField1ActionPerformed);

        empIdLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        empIdLabel1.setText("Employee ID");

        fullNameTextField1.setForeground(new java.awt.Color(204, 204, 204));
        fullNameTextField1.setText(" Jane Smith");
        fullNameTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fullNameTextField1.addActionListener(this::fullNameTextField1ActionPerformed);

        haveAnAccountLabel1.setForeground(new java.awt.Color(51, 102, 255));
        haveAnAccountLabel1.setText("Already have an account? Login");
        haveAnAccountLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        haveAnAccountLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haveAnAccountLabel1MouseClicked(evt);
            }
        });

        emailLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emailLabel1.setText("Email");

        emailTextField1.setForeground(new java.awt.Color(204, 204, 204));
        emailTextField1.setText(" janesmith@example.com");
        emailTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        emailTextField1.addActionListener(this::emailTextField1ActionPerformed);

        signUpBtn1.setBackground(new java.awt.Color(0, 102, 255));
        signUpBtn1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        signUpBtn1.setForeground(new java.awt.Color(255, 255, 255));
        signUpBtn1.setText("Sign Up");
        signUpBtn1.setToolTipText("Press the button to create account");
        signUpBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        signUpBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn1.setName(""); // NOI18N
        signUpBtn1.setOpaque(true);
        signUpBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpBtn1MouseClicked(evt);
            }
        });

        dobLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        dobLabel.setText("Date of Birth");

        dayTextField.setForeground(new java.awt.Color(204, 204, 204));
        dayTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dayTextField.setText("07");
        dayTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "day", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM));
        dayTextField.addActionListener(this::dayTextFieldActionPerformed);

        monthTextField.setForeground(new java.awt.Color(204, 204, 204));
        monthTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monthTextField.setText("10");
        monthTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "month", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM));
        monthTextField.addActionListener(this::monthTextFieldActionPerformed);

        yearTextField.setForeground(new java.awt.Color(204, 204, 204));
        yearTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        yearTextField.setText("1945");
        yearTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "year", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM));
        yearTextField.addActionListener(this::yearTextFieldActionPerformed);

        trnLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        trnLabel.setText("Tax Registration Number");

        trnTextField.setForeground(new java.awt.Color(204, 204, 204));
        trnTextField.setText(" 123456789");
        trnTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        trnTextField.addActionListener(this::trnTextFieldActionPerformed);

        countryLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        countryLabel.setText("Country");

        countryTextField.setForeground(new java.awt.Color(204, 204, 204));
        countryTextField.setText(" Jamaica");
        countryTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        countryTextField.addActionListener(this::countryTextFieldActionPerformed);

        streetLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        streetLabel.setText("Street");

        streetTextField.setForeground(new java.awt.Color(204, 204, 204));
        streetTextField.setText(" Macathy Street");
        streetTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        streetTextField.addActionListener(this::streetTextFieldActionPerformed);

        cityLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cityLabel.setText("City");

        cityTextField.setForeground(new java.awt.Color(204, 204, 204));
        cityTextField.setText(" Montego Bay");
        cityTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cityTextField.addActionListener(this::cityTextFieldActionPerformed);

        genderLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        genderLabel.setText("Gender");

        genderTextField.setForeground(new java.awt.Color(204, 204, 204));
        genderTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        genderTextField.setText(" Male/Female");
        genderTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        genderTextField.addActionListener(this::genderTextFieldActionPerformed);

        parishLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        parishLabel.setText("Parish");

        parishTextField.setForeground(new java.awt.Color(204, 204, 204));
        parishTextField.setText(" St. James");
        parishTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        parishTextField.addActionListener(this::parishTextFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(emailTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fullNameLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fullNameTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(trnTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(trnLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(emailLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(streetTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(streetLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(parishTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(parishLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(empIdTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empIdLabel1)
                            .addComponent(dobLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(countryLabel)
                            .addComponent(cityLabel)
                            .addComponent(countryTextField)
                            .addComponent(cityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signUpInfoLabel1)
                        .addGap(189, 189, 189)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(signUpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(haveAnAccountLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(signUpBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(signUpLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpInfoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIdLabel1)
                    .addComponent(fullNameLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel1)
                    .addComponent(dobLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(trnLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(countryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(streetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(streetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(genderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parishLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parishTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(signUpBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(haveAnAccountLabel1)
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empIdTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIdTextField1ActionPerformed

    private void fullNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTextField1ActionPerformed

    private void haveAnAccountLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAnAccountLabel1MouseClicked
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_haveAnAccountLabel1MouseClicked

    private void emailTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField1ActionPerformed

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void monthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthTextFieldActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void trnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trnTextFieldActionPerformed

    private void countryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldActionPerformed

    private void streetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTextFieldActionPerformed

    private void cityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldActionPerformed

    private void genderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextFieldActionPerformed

    private void parishTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parishTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parishTextFieldActionPerformed

    private void signUpBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBtn1MouseClicked
         
        
        
        
    }//GEN-LAST:event_signUpBtn1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JLabel empIdLabel1;
    private javax.swing.JTextField empIdTextField1;
    private javax.swing.JLabel fullNameLabel1;
    private javax.swing.JTextField fullNameTextField1;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JLabel haveAnAccountLabel1;
    private javax.swing.JTextField monthTextField;
    private javax.swing.JLabel parishLabel;
    private javax.swing.JTextField parishTextField;
    private javax.swing.JButton signUpBtn1;
    private javax.swing.JLabel signUpInfoLabel1;
    private javax.swing.JLabel signUpLabel1;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JLabel trnLabel;
    private javax.swing.JTextField trnTextField;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables

    
public static Connection getConnection() {

    String url = "jdbc:mysql://localhost:3306/payflowdb?useSSL=false&serverTimezone=UTC";
    String username = "root";
    String password = "";  // Your local DB password

    try {
        // Load driver (optional but safer in NetBeans)
        Class.forName("com.mysql.cj.jdbc.Driver");

        myConn = DriverManager.getConnection(url, username, password);

        JOptionPane.showMessageDialog(null,
            "Connection Success",
            "JDBC Connection Status",
            JOptionPane.INFORMATION_MESSAGE
        );

        return myConn;

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null,
            "Connection Failed:\n" + ex.getMessage(),
            "JDBC Error",
            JOptionPane.ERROR_MESSAGE
        );
        ex.printStackTrace();
    }

    return null;
}

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    @Override
    public boolean create(User user) {
      //  throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        return false;
    }

    @Override
    public User delete(User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public User retrieve(User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void update(User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
       
      
    }

    @Override
    public boolean createFull(User user) {
     //   throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
         String sql = "INSERT INTO payflowdb.Staff (id, fullName, email, trn, country, street, city, parish, gender, day, month, year)" + 
                "VALUES ('"+user.getUserId()+"','"+user.getFullName()+"' ,'"+user.getEmail()+"', '"+user.getTrn()+"', '"+user.getCountry()+"', '"+user.getStreet()+"', '"+user.getCity()+"', '"+user.getParish()+"', '"+user.getGender()+"', '"+user.getDay()+"', '"+user.getMonth()+"', '"+user.getYear()+"');";
        try {
            stmt = myConn.createStatement();
        int affectedRows;
            affectedRows = stmt.executeUpdate(sql);
              return affectedRows == 1;
        }catch(SQLSyntaxErrorException ssee){
            System.out.println(ssee.getMessage());
        }catch (SQLException ex) {
            System.getLogger(FullSignUp.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        return false;
    }

    @Override
    public User deleteFull(User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public User retrieveFull(User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void updateFull(User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}


//Custom Methods
