/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.payroll.view;

/**
 *
 * @author school
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form SignUp
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBtn1 = new javax.swing.JButton();
        userOrIdLabel1 = new javax.swing.JLabel();
        userOrIdTextField1 = new javax.swing.JTextField();
        newUserLabel1 = new javax.swing.JLabel();
        loginTitleLabel1 = new javax.swing.JLabel();
        loginFrameInfo1 = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        passwordTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pay FLow Login");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(323, 443));
        setResizable(false);
        setSize(new java.awt.Dimension(323, 443));

        loginBtn1.setBackground(new java.awt.Color(0, 102, 255));
        loginBtn1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        loginBtn1.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn1.setText("Login");
        loginBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        loginBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn1.setOpaque(true);
        loginBtn1.addActionListener(this::loginBtn1ActionPerformed);

        userOrIdLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        userOrIdLabel1.setText("EmployeeID");

        userOrIdTextField1.setForeground(new java.awt.Color(204, 204, 204));
        userOrIdTextField1.setText(" e.g., john.smith or EMP001");
        userOrIdTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        userOrIdTextField1.addActionListener(this::userOrIdTextField1ActionPerformed);

        newUserLabel1.setForeground(new java.awt.Color(51, 102, 255));
        newUserLabel1.setText("New user? Create an account");
        newUserLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newUserLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newUserLabel1createAccountText(evt);
            }
        });

        loginTitleLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        loginTitleLabel1.setForeground(new java.awt.Color(0, 102, 255));
        loginTitleLabel1.setText("Pay Pulse Login");
        loginTitleLabel1.setSize(new java.awt.Dimension(60, 30));

        loginFrameInfo1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        loginFrameInfo1.setForeground(new java.awt.Color(153, 153, 153));
        loginFrameInfo1.setText("Sign in to your account");

        passwordLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        passwordLabel1.setText("Password");

        passwordTextField1.setForeground(new java.awt.Color(204, 204, 204));
        passwordTextField1.setText(" ***********");
        passwordTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passwordTextField1.addActionListener(this::passwordTextField1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userOrIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordLabel1)
                                    .addComponent(userOrIdLabel1)
                                    .addComponent(loginBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(loginFrameInfo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(newUserLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginTitleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginFrameInfo1)
                .addGap(26, 26, 26)
                .addComponent(userOrIdLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userOrIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(passwordLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(loginBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(newUserLabel1)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtn1ActionPerformed
        
    }//GEN-LAST:event_loginBtn1ActionPerformed

    private void userOrIdTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userOrIdTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userOrIdTextField1ActionPerformed

    private void newUserLabel1createAccountText(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserLabel1createAccountText
      this.setVisible(false);
      new SignUp().setVisible(true);
    }//GEN-LAST:event_newUserLabel1createAccountText

    private void passwordTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginBtn1;
    private javax.swing.JLabel loginFrameInfo1;
    private javax.swing.JLabel loginTitleLabel1;
    private javax.swing.JLabel newUserLabel1;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JTextField passwordTextField1;
    private javax.swing.JLabel userOrIdLabel1;
    private javax.swing.JTextField userOrIdTextField1;
    // End of variables declaration//GEN-END:variables
}
