/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.payroll.view;

//import com.java.payroll.connection.DatabaseConn;


/**
 *
 * @author school
 */
public class SignUp extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

    /**
     * Creates new form SignUp
     */
    public SignUp() {
       // DatabaseConn.getConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpLabel1 = new javax.swing.JLabel();
        signUpInfoLabel1 = new javax.swing.JLabel();
        empIdLabel1 = new javax.swing.JLabel();
        empIdTextField1 = new javax.swing.JTextField();
        fullNameLabel1 = new javax.swing.JLabel();
        fullNameTextField1 = new javax.swing.JTextField();
        haveAnAccountLabel1 = new javax.swing.JLabel();
        setPasswordTextField1 = new javax.swing.JTextField();
        setPasswordLabel1 = new javax.swing.JLabel();
        signUpBtn1 = new javax.swing.JButton();
        fullAccountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 530, 673));
        setMinimumSize(new java.awt.Dimension(56, 13));
        setPreferredSize(new java.awt.Dimension(530, 673));
        setResizable(false);
        setSize(new java.awt.Dimension(530, 673));

        signUpLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        signUpLabel1.setForeground(new java.awt.Color(0, 102, 255));
        signUpLabel1.setText("Pay Pulse Sign Up");
        signUpLabel1.setSize(new java.awt.Dimension(60, 30));

        signUpInfoLabel1.setFont(new java.awt.Font("DecoType Naskh", 0, 14)); // NOI18N
        signUpInfoLabel1.setForeground(new java.awt.Color(153, 153, 153));
        signUpInfoLabel1.setText("Register your account");

        empIdLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        empIdLabel1.setText("Employee ID (Must Exist)");

        empIdTextField1.setForeground(new java.awt.Color(204, 204, 204));
        empIdTextField1.setText(" EMP001");
        empIdTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        empIdTextField1.addActionListener(this::empIdTextField1ActionPerformed);

        fullNameLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fullNameLabel1.setText("Full Name");

        fullNameTextField1.setForeground(new java.awt.Color(204, 204, 204));
        fullNameTextField1.setText(" Jane Smith");
        fullNameTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fullNameTextField1.addActionListener(this::fullNameTextField1ActionPerformed);

        haveAnAccountLabel1.setForeground(new java.awt.Color(51, 102, 255));
        haveAnAccountLabel1.setText("Already have an account? Login");
        haveAnAccountLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        haveAnAccountLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haveAnAccountLabel1MouseClicked(evt);
            }
        });

        setPasswordTextField1.setForeground(new java.awt.Color(204, 204, 204));
        setPasswordTextField1.setText(" ***********");
        setPasswordTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setPasswordTextField1.addActionListener(this::setPasswordTextField1ActionPerformed);

        setPasswordLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        setPasswordLabel1.setText("Set Password");

        signUpBtn1.setBackground(new java.awt.Color(0, 102, 255));
        signUpBtn1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        signUpBtn1.setForeground(new java.awt.Color(255, 255, 255));
        signUpBtn1.setText("Sign Up");
        signUpBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        signUpBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn1.setOpaque(true);
        signUpBtn1.addActionListener(this::signUpBtn1ActionPerformed);

        fullAccountLabel.setForeground(new java.awt.Color(51, 102, 255));
        fullAccountLabel.setText("Register full account?");
        fullAccountLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fullAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullAccountLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(setPasswordLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empIdLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullNameLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fullNameTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empIdTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setPasswordTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signUpLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(signUpBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(haveAnAccountLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(signUpInfoLabel1)))
                        .addGap(0, 111, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fullAccountLabel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(signUpLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signUpInfoLabel1)
                .addGap(28, 28, 28)
                .addComponent(fullNameLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(empIdLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empIdTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(setPasswordLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setPasswordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(signUpBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(haveAnAccountLabel1)
                .addGap(34, 34, 34)
                .addComponent(fullAccountLabel)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void empIdTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIdTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIdTextField1ActionPerformed

    private void fullNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTextField1ActionPerformed

    private void haveAnAccountLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haveAnAccountLabel1MouseClicked
       this.setVisible(false);
       new Login().setVisible(true);
    }//GEN-LAST:event_haveAnAccountLabel1MouseClicked

    private void setPasswordTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPasswordTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setPasswordTextField1ActionPerformed

    private void signUpBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signUpBtn1ActionPerformed

    private void fullAccountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullAccountLabelMouseClicked
        this.setVisible(false);
        new FullSignUp().setVisible(true);
    }//GEN-LAST:event_fullAccountLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel empIdLabel1;
    private javax.swing.JTextField empIdTextField1;
    private javax.swing.JLabel fullAccountLabel;
    private javax.swing.JLabel fullNameLabel1;
    private javax.swing.JTextField fullNameTextField1;
    private javax.swing.JLabel haveAnAccountLabel1;
    private javax.swing.JLabel setPasswordLabel1;
    private javax.swing.JTextField setPasswordTextField1;
    private javax.swing.JButton signUpBtn1;
    private javax.swing.JLabel signUpInfoLabel1;
    private javax.swing.JLabel signUpLabel1;
    // End of variables declaration//GEN-END:variables
}

//Custom Methods

