/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.payroll.employee;

/**
 *
 * @author school
 */
public class RegEmployeeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegEmployeeFrame.class.getName());

    /**
     * Creates new form RegEmployeeFrame
     */
    public RegEmployeeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empScrollPane = new javax.swing.JScrollPane();
        employeeTabPane = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        hoursWorkedMiniPanel1 = new javax.swing.JPanel();
        hoursWorkedCurMnthLabel1 = new javax.swing.JLabel();
        hoursValueLabel1 = new javax.swing.JLabel();
        hoursTextLabel1 = new javax.swing.JLabel();
        nextPayDatePanel1 = new javax.swing.JPanel();
        nextPayDateLabel1 = new javax.swing.JLabel();
        nextPayDateVal1 = new javax.swing.JLabel();
        nextPayDateText1 = new javax.swing.JLabel();
        lastPayslipPanel1 = new javax.swing.JPanel();
        lastPayslipDateLabel1 = new javax.swing.JLabel();
        lastPayslipDateValue1 = new javax.swing.JLabel();
        lastPayslipText1 = new javax.swing.JLabel();
        row2Panel = new javax.swing.JPanel();
        quickActionsPanel = new javax.swing.JPanel();
        quickSelfPanel = new javax.swing.JPanel();
        quickSelfServiceLabel = new javax.swing.JLabel();
        servicesPanel = new javax.swing.JPanel();
        quickSelf1 = new javax.swing.JPanel();
        innerQSPanel1 = new javax.swing.JPanel();
        payslipIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        innerQSPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        quickSelf2 = new javax.swing.JPanel();
        innerQSPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        innerQSPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        quickSelf3 = new javax.swing.JPanel();
        innerQSPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        innerQSPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        quickSelf4 = new javax.swing.JPanel();
        innerQSPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        innerQSPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        dashAnnouncementsPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        announcementsLabel = new javax.swing.JLabel();
        announcementsInternalFrame = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        myAnnouncementTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        companyAnnouncementsTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        sysMaintenanceTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        announcementsLabel1 = new javax.swing.JLabel();
        activityTimeLineInternalFrame = new javax.swing.JInternalFrame();
        myAnnouncementTab1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        workingHrsTab = new javax.swing.JPanel();
        accessPayslipsTab = new javax.swing.JPanel();
        requestStatInfoTab = new javax.swing.JPanel();
        requestBenefitsTab = new javax.swing.JPanel();
        myExpenseProjectionTab = new javax.swing.JPanel();
        salaryCalculatorTab = new javax.swing.JPanel();
        requestPayrollDataTab = new javax.swing.JPanel();
        announcementsTab = new javax.swing.JPanel();
        empTopPanel = new javax.swing.JPanel();
        empWelcomeLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        empScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        empScrollPane.setPreferredSize(new java.awt.Dimension(1920, 1080));

        employeeTabPane.setBackground(new java.awt.Color(255, 255, 255));
        employeeTabPane.setBorder(new javax.swing.border.MatteBorder(null));
        employeeTabPane.setForeground(new java.awt.Color(0, 102, 255));
        employeeTabPane.setToolTipText("Employee Dashboard");
        employeeTabPane.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        employeeTabPane.setOpaque(true);

        dashboardTab.setBackground(new java.awt.Color(255, 255, 255));
        dashboardTab.setPreferredSize(new java.awt.Dimension(1920, 1080));
        dashboardTab.setLayout(new java.awt.BorderLayout(0, 100));

        jPanel6.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(1920, 128));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        hoursWorkedMiniPanel1.setBackground(new java.awt.Color(153, 204, 255));
        hoursWorkedMiniPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hoursWorkedMiniPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hoursWorkedMiniPanel1.setLayout(new java.awt.BorderLayout(0, 10));

        hoursWorkedCurMnthLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        hoursWorkedCurMnthLabel1.setForeground(new java.awt.Color(255, 255, 255));
        hoursWorkedCurMnthLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoursWorkedCurMnthLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/time-check.png"))); // NOI18N
        hoursWorkedCurMnthLabel1.setText("Total Hours Worked, {month}");
        hoursWorkedCurMnthLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        hoursWorkedMiniPanel1.add(hoursWorkedCurMnthLabel1, java.awt.BorderLayout.NORTH);

        hoursValueLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        hoursValueLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoursValueLabel1.setText("{get Hours worked}");
        hoursWorkedMiniPanel1.add(hoursValueLabel1, java.awt.BorderLayout.CENTER);

        hoursTextLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        hoursTextLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoursTextLabel1.setText("{percentage} completed of the month's expected hours.");
        hoursWorkedMiniPanel1.add(hoursTextLabel1, java.awt.BorderLayout.SOUTH);

        jPanel6.add(hoursWorkedMiniPanel1);

        nextPayDatePanel1.setBackground(new java.awt.Color(153, 204, 255));
        nextPayDatePanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nextPayDatePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextPayDatePanel1.setLayout(new java.awt.BorderLayout());

        nextPayDateLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        nextPayDateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nextPayDateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextPayDateLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar-day-2.png"))); // NOI18N
        nextPayDateLabel1.setText("Next Pay Date");
        nextPayDateLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nextPayDatePanel1.add(nextPayDateLabel1, java.awt.BorderLayout.PAGE_START);

        nextPayDateVal1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        nextPayDateVal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextPayDateVal1.setText("{date}");
        nextPayDatePanel1.add(nextPayDateVal1, java.awt.BorderLayout.CENTER);

        nextPayDateText1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        nextPayDateText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nextPayDateText1.setText("Be sure to submit yours hours by the 18th.");
        nextPayDatePanel1.add(nextPayDateText1, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(nextPayDatePanel1);

        lastPayslipPanel1.setBackground(new java.awt.Color(153, 204, 255));
        lastPayslipPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lastPayslipPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lastPayslipPanel1.setLayout(new java.awt.BorderLayout());

        lastPayslipDateLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lastPayslipDateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        lastPayslipDateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastPayslipDateLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money-bills-simple.png"))); // NOI18N
        lastPayslipDateLabel1.setText("Last Payslip Date");
        lastPayslipDateLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lastPayslipPanel1.add(lastPayslipDateLabel1, java.awt.BorderLayout.PAGE_START);

        lastPayslipDateValue1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lastPayslipDateValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastPayslipDateValue1.setText("{date}");
        lastPayslipPanel1.add(lastPayslipDateValue1, java.awt.BorderLayout.CENTER);

        lastPayslipText1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lastPayslipText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastPayslipText1.setText("Date of the last payslip received.");
        lastPayslipPanel1.add(lastPayslipText1, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(lastPayslipPanel1);

        dashboardTab.add(jPanel6, java.awt.BorderLayout.NORTH);

        row2Panel.setPreferredSize(new java.awt.Dimension(4277, 974));
        row2Panel.setLayout(new java.awt.BorderLayout(0, 10));

        quickActionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        quickActionsPanel.setLayout(new java.awt.BorderLayout(0, 40));

        quickSelfPanel.setBackground(new java.awt.Color(255, 255, 255));
        quickSelfPanel.setLayout(new java.awt.BorderLayout());

        quickSelfServiceLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        quickSelfServiceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quickSelfServiceLabel.setText("Quick Self-Service");
        quickSelfPanel.add(quickSelfServiceLabel, java.awt.BorderLayout.CENTER);

        quickActionsPanel.add(quickSelfPanel, java.awt.BorderLayout.NORTH);

        servicesPanel.setLayout(new java.awt.GridLayout(1, 0));

        quickSelf1.setBackground(new java.awt.Color(255, 255, 255));
        quickSelf1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        innerQSPanel1.setBackground(new java.awt.Color(255, 255, 255));
        innerQSPanel1.setLayout(new java.awt.BorderLayout());

        payslipIcon.setBackground(new java.awt.Color(255, 255, 255));
        payslipIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        payslipIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/features.png"))); // NOI18N
        payslipIcon.setAlignmentX(0.5F);
        payslipIcon.setOpaque(true);
        innerQSPanel1.add(payslipIcon, java.awt.BorderLayout.NORTH);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Playslips");
        jLabel3.setOpaque(true);
        innerQSPanel1.add(jLabel3, java.awt.BorderLayout.CENTER);

        innerQSPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("View or export your lates pay information");
        jLabel2.setOpaque(true);
        innerQSPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton1.setText("Go to Payslips");
        jButton1.setBounds(new java.awt.Rectangle(0, 0, 78, 23));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(50, 29));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        innerQSPanel2.add(jButton1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout quickSelf1Layout = new javax.swing.GroupLayout(quickSelf1);
        quickSelf1.setLayout(quickSelf1Layout);
        quickSelf1Layout.setHorizontalGroup(
            quickSelf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerQSPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(innerQSPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        quickSelf1Layout.setVerticalGroup(
            quickSelf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickSelf1Layout.createSequentialGroup()
                .addComponent(innerQSPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(innerQSPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        servicesPanel.add(quickSelf1);

        quickSelf2.setBackground(new java.awt.Color(255, 255, 255));
        quickSelf2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        innerQSPanel3.setBackground(new java.awt.Color(255, 255, 255));
        innerQSPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gift-box-benefits.png"))); // NOI18N
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setOpaque(true);
        innerQSPanel3.add(jLabel4, java.awt.BorderLayout.NORTH);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Benefits");
        jLabel5.setOpaque(true);
        innerQSPanel3.add(jLabel5, java.awt.BorderLayout.CENTER);

        innerQSPanel4.setLayout(new java.awt.BorderLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Request new or update existing benefits");
        jLabel6.setOpaque(true);
        innerQSPanel4.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton2.setText("Go to Benefits");
        jButton2.setBounds(new java.awt.Rectangle(0, 0, 78, 23));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);
        jButton2.setPreferredSize(new java.awt.Dimension(50, 29));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        innerQSPanel4.add(jButton2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout quickSelf2Layout = new javax.swing.GroupLayout(quickSelf2);
        quickSelf2.setLayout(quickSelf2Layout);
        quickSelf2Layout.setHorizontalGroup(
            quickSelf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerQSPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(innerQSPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        quickSelf2Layout.setVerticalGroup(
            quickSelf2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickSelf2Layout.createSequentialGroup()
                .addComponent(innerQSPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(innerQSPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        servicesPanel.add(quickSelf2);

        quickSelf3.setBackground(new java.awt.Color(153, 255, 255));
        quickSelf3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        innerQSPanel5.setBackground(new java.awt.Color(255, 255, 255));
        innerQSPanel5.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/checklist-task-budget.png"))); // NOI18N
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setOpaque(true);
        innerQSPanel5.add(jLabel7, java.awt.BorderLayout.NORTH);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Budget");
        jLabel8.setOpaque(true);
        innerQSPanel5.add(jLabel8, java.awt.BorderLayout.CENTER);

        innerQSPanel6.setLayout(new java.awt.BorderLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("View or export your lates pay information");
        jLabel9.setOpaque(true);
        innerQSPanel6.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton3.setText("Go to Budget");
        jButton3.setBounds(new java.awt.Rectangle(0, 0, 78, 23));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setOpaque(true);
        jButton3.setPreferredSize(new java.awt.Dimension(50, 29));
        jButton3.addActionListener(this::jButton3ActionPerformed);
        innerQSPanel6.add(jButton3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout quickSelf3Layout = new javax.swing.GroupLayout(quickSelf3);
        quickSelf3.setLayout(quickSelf3Layout);
        quickSelf3Layout.setHorizontalGroup(
            quickSelf3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerQSPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(innerQSPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        quickSelf3Layout.setVerticalGroup(
            quickSelf3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickSelf3Layout.createSequentialGroup()
                .addComponent(innerQSPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(innerQSPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        servicesPanel.add(quickSelf3);

        quickSelf4.setBackground(new java.awt.Color(153, 0, 255));
        quickSelf4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        innerQSPanel7.setBackground(new java.awt.Color(255, 255, 255));
        innerQSPanel7.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock-three.png"))); // NOI18N
        jLabel10.setAlignmentX(0.5F);
        jLabel10.setOpaque(true);
        innerQSPanel7.add(jLabel10, java.awt.BorderLayout.NORTH);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Working Hours");
        jLabel11.setOpaque(true);
        innerQSPanel7.add(jLabel11, java.awt.BorderLayout.CENTER);

        innerQSPanel8.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("View or export your lates pay information");
        jLabel12.setOpaque(true);
        innerQSPanel8.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        jButton4.setBackground(new java.awt.Color(153, 204, 255));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton4.setText("Go to Working Hours");
        jButton4.setBounds(new java.awt.Rectangle(0, 0, 78, 23));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setOpaque(true);
        jButton4.setPreferredSize(new java.awt.Dimension(50, 29));
        jButton4.addActionListener(this::jButton4ActionPerformed);
        innerQSPanel8.add(jButton4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout quickSelf4Layout = new javax.swing.GroupLayout(quickSelf4);
        quickSelf4.setLayout(quickSelf4Layout);
        quickSelf4Layout.setHorizontalGroup(
            quickSelf4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerQSPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(innerQSPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        quickSelf4Layout.setVerticalGroup(
            quickSelf4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quickSelf4Layout.createSequentialGroup()
                .addComponent(innerQSPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(innerQSPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        servicesPanel.add(quickSelf4);

        quickActionsPanel.add(servicesPanel, java.awt.BorderLayout.CENTER);

        dashAnnouncementsPanel.setBackground(new java.awt.Color(51, 255, 153));
        dashAnnouncementsPanel.setPreferredSize(new java.awt.Dimension(1920, 500));
        dashAnnouncementsPanel.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setLayout(new java.awt.BorderLayout());

        announcementsLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        announcementsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        announcementsLabel.setText("Announcements");
        jPanel5.add(announcementsLabel, java.awt.BorderLayout.NORTH);

        announcementsInternalFrame.setBackground(new java.awt.Color(153, 204, 255));
        announcementsInternalFrame.setIconifiable(true);
        announcementsInternalFrame.setMaximizable(true);
        announcementsInternalFrame.setResizable(true);
        announcementsInternalFrame.setTitle("Payflow Announcements");
        announcementsInternalFrame.setToolTipText("View all company announcements here.");
        announcementsInternalFrame.setOpaque(true);
        announcementsInternalFrame.setVisible(true);

        myAnnouncementTab.setLayout(new java.awt.GridLayout());

        jTextArea1.setColumns(50);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(30);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        myAnnouncementTab.add(jScrollPane1);

        jTabbedPane1.addTab("My Announcements", myAnnouncementTab);

        companyAnnouncementsTab.setLayout(new java.awt.GridLayout());

        jTextArea2.setColumns(50);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(30);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        companyAnnouncementsTab.add(jScrollPane2);

        jTabbedPane1.addTab("Company Announcements", companyAnnouncementsTab);

        sysMaintenanceTab.setLayout(new java.awt.GridLayout());

        jTextArea3.setColumns(50);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(30);
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        sysMaintenanceTab.add(jScrollPane3);

        jTabbedPane1.addTab("System Maintenance", sysMaintenanceTab);

        jButton5.setText("Refresh");
        jTabbedPane1.addTab("Refresh", jButton5);

        javax.swing.GroupLayout announcementsInternalFrameLayout = new javax.swing.GroupLayout(announcementsInternalFrame.getContentPane());
        announcementsInternalFrame.getContentPane().setLayout(announcementsInternalFrameLayout);
        announcementsInternalFrameLayout.setHorizontalGroup(
            announcementsInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        announcementsInternalFrameLayout.setVerticalGroup(
            announcementsInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        jPanel5.add(announcementsInternalFrame, java.awt.BorderLayout.CENTER);
        try {
            announcementsInternalFrame.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        dashAnnouncementsPanel.add(jPanel5);

        jPanel7.setLayout(new java.awt.BorderLayout());

        announcementsLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        announcementsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        announcementsLabel1.setText("Activity Timeline");
        jPanel7.add(announcementsLabel1, java.awt.BorderLayout.NORTH);

        activityTimeLineInternalFrame.setBackground(new java.awt.Color(153, 204, 255));
        activityTimeLineInternalFrame.setIconifiable(true);
        activityTimeLineInternalFrame.setMaximizable(true);
        activityTimeLineInternalFrame.setResizable(true);
        activityTimeLineInternalFrame.setTitle("My Logs");
        activityTimeLineInternalFrame.setToolTipText("Your log in infomation per day");
        activityTimeLineInternalFrame.setOpaque(true);
        activityTimeLineInternalFrame.setVisible(true);

        myAnnouncementTab1.setLayout(new java.awt.GridLayout());

        jTextArea4.setColumns(50);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(30);
        jTextArea4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea4);

        myAnnouncementTab1.add(jScrollPane4);

        javax.swing.GroupLayout activityTimeLineInternalFrameLayout = new javax.swing.GroupLayout(activityTimeLineInternalFrame.getContentPane());
        activityTimeLineInternalFrame.getContentPane().setLayout(activityTimeLineInternalFrameLayout);
        activityTimeLineInternalFrameLayout.setHorizontalGroup(
            activityTimeLineInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
            .addGroup(activityTimeLineInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(activityTimeLineInternalFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(myAnnouncementTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        activityTimeLineInternalFrameLayout.setVerticalGroup(
            activityTimeLineInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
            .addGroup(activityTimeLineInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(activityTimeLineInternalFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(myAnnouncementTab1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel7.add(activityTimeLineInternalFrame, java.awt.BorderLayout.CENTER);

        dashAnnouncementsPanel.add(jPanel7);

        quickActionsPanel.add(dashAnnouncementsPanel, java.awt.BorderLayout.SOUTH);

        row2Panel.add(quickActionsPanel, java.awt.BorderLayout.NORTH);

        dashboardTab.add(row2Panel, java.awt.BorderLayout.CENTER);

        employeeTabPane.addTab("Dashboard", dashboardTab);

        javax.swing.GroupLayout workingHrsTabLayout = new javax.swing.GroupLayout(workingHrsTab);
        workingHrsTab.setLayout(workingHrsTabLayout);
        workingHrsTabLayout.setHorizontalGroup(
            workingHrsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        workingHrsTabLayout.setVerticalGroup(
            workingHrsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        employeeTabPane.addTab("View Working Hours", workingHrsTab);

        javax.swing.GroupLayout accessPayslipsTabLayout = new javax.swing.GroupLayout(accessPayslipsTab);
        accessPayslipsTab.setLayout(accessPayslipsTabLayout);
        accessPayslipsTabLayout.setHorizontalGroup(
            accessPayslipsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        accessPayslipsTabLayout.setVerticalGroup(
            accessPayslipsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        employeeTabPane.addTab("Access Payslips", accessPayslipsTab);

        javax.swing.GroupLayout requestStatInfoTabLayout = new javax.swing.GroupLayout(requestStatInfoTab);
        requestStatInfoTab.setLayout(requestStatInfoTabLayout);
        requestStatInfoTabLayout.setHorizontalGroup(
            requestStatInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        requestStatInfoTabLayout.setVerticalGroup(
            requestStatInfoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        employeeTabPane.addTab("Request Statutory Info", requestStatInfoTab);

        javax.swing.GroupLayout requestBenefitsTabLayout = new javax.swing.GroupLayout(requestBenefitsTab);
        requestBenefitsTab.setLayout(requestBenefitsTabLayout);
        requestBenefitsTabLayout.setHorizontalGroup(
            requestBenefitsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        requestBenefitsTabLayout.setVerticalGroup(
            requestBenefitsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        employeeTabPane.addTab("Request Benefits", requestBenefitsTab);

        javax.swing.GroupLayout myExpenseProjectionTabLayout = new javax.swing.GroupLayout(myExpenseProjectionTab);
        myExpenseProjectionTab.setLayout(myExpenseProjectionTabLayout);
        myExpenseProjectionTabLayout.setHorizontalGroup(
            myExpenseProjectionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        myExpenseProjectionTabLayout.setVerticalGroup(
            myExpenseProjectionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        employeeTabPane.addTab("My Expense Projection", myExpenseProjectionTab);

        javax.swing.GroupLayout salaryCalculatorTabLayout = new javax.swing.GroupLayout(salaryCalculatorTab);
        salaryCalculatorTab.setLayout(salaryCalculatorTabLayout);
        salaryCalculatorTabLayout.setHorizontalGroup(
            salaryCalculatorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        salaryCalculatorTabLayout.setVerticalGroup(
            salaryCalculatorTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        employeeTabPane.addTab("Salary Calculator", salaryCalculatorTab);

        javax.swing.GroupLayout requestPayrollDataTabLayout = new javax.swing.GroupLayout(requestPayrollDataTab);
        requestPayrollDataTab.setLayout(requestPayrollDataTabLayout);
        requestPayrollDataTabLayout.setHorizontalGroup(
            requestPayrollDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        requestPayrollDataTabLayout.setVerticalGroup(
            requestPayrollDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        employeeTabPane.addTab("Request Payroll Data", requestPayrollDataTab);

        javax.swing.GroupLayout announcementsTabLayout = new javax.swing.GroupLayout(announcementsTab);
        announcementsTab.setLayout(announcementsTabLayout);
        announcementsTabLayout.setHorizontalGroup(
            announcementsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        announcementsTabLayout.setVerticalGroup(
            announcementsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        employeeTabPane.addTab("Announcements", announcementsTab);

        empScrollPane.setViewportView(employeeTabPane);
        employeeTabPane.getAccessibleContext().setAccessibleName("Dashboard");
        employeeTabPane.getAccessibleContext().setAccessibleDescription("");

        empTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        empTopPanel.setLayout(new java.awt.BorderLayout());

        empWelcomeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        empWelcomeLabel.setForeground(new java.awt.Color(0, 102, 255));
        empWelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empWelcomeLabel.setText("Welcome {employee}");
        empTopPanel.add(empWelcomeLabel, java.awt.BorderLayout.CENTER);

        logoutBtn.setBackground(new java.awt.Color(255, 102, 102));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/leave.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logoutBtn.addActionListener(this::logoutBtnActionPerformed);
        empTopPanel.add(logoutBtn, java.awt.BorderLayout.LINE_END);

        jComboBox1.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 153, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "View Profile", "Settings", "Restart", "Help" }));
        jComboBox1.setToolTipText("Additional options ");
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jComboBox1.setOpaque(true);
        empTopPanel.add(jComboBox1, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(empTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(empTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(empScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegEmployeeFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accessPayslipsTab;
    private javax.swing.JInternalFrame activityTimeLineInternalFrame;
    private javax.swing.JInternalFrame announcementsInternalFrame;
    private javax.swing.JLabel announcementsLabel;
    private javax.swing.JLabel announcementsLabel1;
    private javax.swing.JPanel announcementsTab;
    private javax.swing.JPanel companyAnnouncementsTab;
    private javax.swing.JPanel dashAnnouncementsPanel;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JScrollPane empScrollPane;
    private javax.swing.JPanel empTopPanel;
    private javax.swing.JLabel empWelcomeLabel;
    private javax.swing.JTabbedPane employeeTabPane;
    private javax.swing.JLabel hoursTextLabel1;
    private javax.swing.JLabel hoursValueLabel1;
    private javax.swing.JLabel hoursWorkedCurMnthLabel1;
    private javax.swing.JPanel hoursWorkedMiniPanel1;
    private javax.swing.JPanel innerQSPanel1;
    private javax.swing.JPanel innerQSPanel2;
    private javax.swing.JPanel innerQSPanel3;
    private javax.swing.JPanel innerQSPanel4;
    private javax.swing.JPanel innerQSPanel5;
    private javax.swing.JPanel innerQSPanel6;
    private javax.swing.JPanel innerQSPanel7;
    private javax.swing.JPanel innerQSPanel8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel lastPayslipDateLabel1;
    private javax.swing.JLabel lastPayslipDateValue1;
    private javax.swing.JPanel lastPayslipPanel1;
    private javax.swing.JLabel lastPayslipText1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel myAnnouncementTab;
    private javax.swing.JPanel myAnnouncementTab1;
    private javax.swing.JPanel myExpenseProjectionTab;
    private javax.swing.JLabel nextPayDateLabel1;
    private javax.swing.JPanel nextPayDatePanel1;
    private javax.swing.JLabel nextPayDateText1;
    private javax.swing.JLabel nextPayDateVal1;
    private javax.swing.JLabel payslipIcon;
    private javax.swing.JPanel quickActionsPanel;
    private javax.swing.JPanel quickSelf1;
    private javax.swing.JPanel quickSelf2;
    private javax.swing.JPanel quickSelf3;
    private javax.swing.JPanel quickSelf4;
    private javax.swing.JPanel quickSelfPanel;
    private javax.swing.JLabel quickSelfServiceLabel;
    private javax.swing.JPanel requestBenefitsTab;
    private javax.swing.JPanel requestPayrollDataTab;
    private javax.swing.JPanel requestStatInfoTab;
    private javax.swing.JPanel row2Panel;
    private javax.swing.JPanel salaryCalculatorTab;
    private javax.swing.JPanel servicesPanel;
    private javax.swing.JPanel sysMaintenanceTab;
    private javax.swing.JPanel workingHrsTab;
    // End of variables declaration//GEN-END:variables
}
